# Import Data and Required Packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv("E:\Downloads\data.csv")

In [5]:
df

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.952560,2.15000,0.007972,-0.048340,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,20-May-18,26-Aug-18,Alive
1,54,FEMALE,0.000000,1.38020,-0.498030,-0.507320,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,26-Apr-18,25-Jan-19,Dead
2,63,FEMALE,-0.523030,1.76400,-0.370190,0.010815,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,24-Aug-18,08-Apr-20,Alive
3,78,FEMALE,-0.876180,0.12943,-0.370380,0.132190,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,16-Nov-18,28-Jul-20,Alive
4,42,FEMALE,0.226110,1.74910,-0.543970,-0.390210,II,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,12-Dec-18,05-Jan-19,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,59,FEMALE,0.024598,1.40050,0.024751,0.280320,II,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,15-Jan-19,27-Mar-20,Alive
330,41,FEMALE,0.100120,-0.46547,0.472370,-0.523870,I,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Modified Radical Mastectomy,25-Jul-18,23-Apr-19,Alive
331,54,FEMALE,0.753820,1.64250,-0.332850,0.857860,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Simple Mastectomy,26-Mar-19,11-Oct-19,Dead
332,74,FEMALE,0.972510,1.42680,-0.366570,-0.107820,II,Infiltrating Lobular Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Nov-18,05-Dec-18,Alive
333,66,FEMALE,0.286380,1.39980,0.318830,0.836050,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,04-Feb-19,10-Aug-19,Dead

# clinical /Diagnostics(Medical) data

In [ ]:
#clinical --->
#age
#gender
#tumar_stage -> level of cancer
#Stage 1 → low
#stage2 -> moderate
#Stage3 ->high chances
#Surgery_type → कौन सा operation हुआ
#Date_of_Surgery → date of surgery
#Date_of_Last_Visit → last checkup

#Diagnostic--->
# Protein1
# Protein2
# Protein3
# Protein4
# Histology
# ER status
# PR status
# HER2 status

In [6]:
df.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,42,FEMALE,0.95256,2.15000,0.007972,-0.048340,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,20-May-18,26-Aug-18,Alive
1,54,FEMALE,0.00000,1.38020,-0.498030,-0.507320,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,26-Apr-18,25-Jan-19,Dead
2,63,FEMALE,-0.52303,1.76400,-0.370190,0.010815,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,24-Aug-18,08-Apr-20,Alive
3,78,FEMALE,-0.87618,0.12943,-0.370380,0.132190,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,16-Nov-18,28-Jul-20,Alive
4,42,FEMALE,0.22611,1.74910,-0.543970,-0.390210,II,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,12-Dec-18,05-Jan-19,Alive

In [7]:
df.tail()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
329,59,FEMALE,0.024598,1.40050,0.024751,0.28032,II,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,15-Jan-19,27-Mar-20,Alive
330,41,FEMALE,0.100120,-0.46547,0.472370,-0.52387,I,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Modified Radical Mastectomy,25-Jul-18,23-Apr-19,Alive
331,54,FEMALE,0.753820,1.64250,-0.332850,0.85786,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Simple Mastectomy,26-Mar-19,11-Oct-19,Dead
332,74,FEMALE,0.972510,1.42680,-0.366570,-0.10782,II,Infiltrating Lobular Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Nov-18,05-Dec-18,Alive
333,66,FEMALE,0.286380,1.39980,0.318830,0.83605,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,04-Feb-19,10-Aug-19,Dead

In [8]:
df.shape

(334, 15)

In [10]:
df.size

5010

In [24]:
df.columns

Index(['Age', 'Gender', 'Protein1', 'Protein2', 'Protein3', 'Protein4',
       'Tumour_Stage', 'Histology', 'ER status', 'PR status', 'HER2 status',
       'Surgery_type', 'Date_of_Surgery', 'Date_of_Last_Visit',
       'Patient_Status'],
      dtype='object')

In [11]:
df.isnull().sum()

Age                    0
Gender                 0
Protein1               0
Protein2               0
Protein3               0
Protein4               0
Tumour_Stage           0
Histology              0
ER status              0
PR status              0
HER2 status            0
Surgery_type           0
Date_of_Surgery        0
Date_of_Last_Visit    17
Patient_Status        13
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 334 non-null    int64
 1   Gender              334 non-null    object
 2   Protein1            334 non-null    float64
 3   Protein2            334 non-null    float64
 4   Protein3            334 non-null    float64
 5   Protein4            334 non-null    float64
 6   Tumour_Stage        334 non-null    object
 7   Histology           334 non-null    object
 8   ER status           334 non-null    object
 9   PR status           334 non-null    object
 10  HER2 status         334 non-null    object
 11  Surgery_type        334 non-null    object
 12  Date_of_Surgery     334 non-null    object
 13  Date_of_Last_Visit  317 non-null    object
 14  Patient_Status      321 non-null    object
dtypes: float64(4), int64(1), object(10)
memory usage: 39.3+ KB

# Checking the number of unique values of each column

In [18]:
df.nunique()

Age                    57
Gender                  2
Protein1              333
Protein2              334
Protein3              334
Protein4              333
Tumour_Stage            3
Histology               3
ER status               1
PR status               1
HER2 status             2
Surgery_type            4
Date_of_Surgery       181
Date_of_Last_Visit    285
Patient_Status          2
dtype: int64

In [22]:
df.describe()

              Age    Protein1    Protein2    Protein3    Protein4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean    58.886228   -0.029991    0.946896   -0.090204    0.009819
std     12.961212    0.563588    0.911637    0.585175    0.629055
min     29.000000   -2.340900   -0.978730   -1.627400   -2.025500
25%     49.000000   -0.358888    0.362173   -0.513748   -0.377090
50%     58.000000    0.006129    0.992805   -0.173180    0.041768
75%     68.000000    0.343598    1.627900    0.278353    0.425630
max     90.000000    1.593600    3.402200    2.193400    1.629900

In [21]:
df.describe(include="all")

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
count,334.000000,334,334.000000,334.000000,334.000000,334.000000,334,334,334,334,334,334,334,317,321
unique,NaN,2,NaN,NaN,NaN,NaN,3,3,1,1,2,4,181,285,2
top,NaN,FEMALE,NaN,NaN,NaN,NaN,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,16-Nov-18,13-Feb-21,Alive
freq,NaN,330,NaN,NaN,NaN,NaN,189,233,334,334,305,105,5,3,255
mean,58.886228,NaN,-0.029991,0.946896,-0.090204,0.009819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,12.961212,NaN,0.563588,0.911637,0.585175,0.629055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,29.000000,NaN,-2.340900,-0.978730,-1.627400,-2.025500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,49.000000,NaN,-0.358888,0.362173,-0.513748,-0.377090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,58.000000,NaN,0.006129,0.992805,-0.173180,0.041768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,68.000000,NaN,0.343598,1.627900,0.278353,0.425630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,90.000000,NaN,1.593600,3.402200,2.193400,1.629900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
!pip install pandas-profiling

Collecting pandas-profiling
  Downloading pandas_profiling-3.2.0-py2.py3-none-any.whl.metadata (21 kB)
Collecting joblib~=1.1.0 (from pandas-profiling)
  Downloading joblib-1.1.1-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: scipy>=1.4.1 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from pandas-profiling) (1.16.2)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from pandas-profiling) (2.3.1)
Requirement already satisfied: matplotlib>=3.2.0 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from pandas-profiling) (3.10.7)
Requirement already satisfied: pydantic>=1.8.1 in C:\Users\DELL\anaconda3\Lib\site-packages (from pandas-profiling) (2.10.3)
Requirement already satisfied: PyYAML>=5.0.0 in C:\Users\DELL\anaconda3\Lib\site-packages (from pandas-profiling) (6.0.2)
Requirement already satisfied: jinja2>=2.11.1 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from pandas-profiling) (3.1.6)
Collecting markupsafe~=2.1.1 (from pandas-profiling)
  Downloading MarkupSafe-2.1.5.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting visions==0.7.4 (from visions[type_image_path]==0.7.4->pandas-profiling)
  Downloading visions-0.7.4-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.16.0 in C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages (from pandas-profiling) (2.2.6)
Collecting htmlmin>=0.1.12 (from pandas-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [27 lines of output]
  Traceback (most recent call last):
    File "C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\DELL\AppData\Roaming\Python\Python313\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-t6xggyv1\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-t6xggyv1\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-t6xggyv1\overlay\Lib\site-packages\setuptools\build_meta.py", line 520, in run_setup
      super().run_setup(setup_script=setup_script)
      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\DELL\AppData\Local\Temp\pip-build-env-t6xggyv1\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 4, in <module>
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-litm_8qa\htmlmin_d2236b415d6b4ccc8327757e3a2f453f\htmlmin\__init__.py", line 28, in <module>
      from .main import minify, Minifier
    File "C:\Users\DELL\AppData\Local\Temp\pip-install-litm_8qa\htmlmin_d2236b415d6b4ccc8327757e3a2f453f\htmlmin\main.py", line 28, in <module>
      import cgi
  ModuleNotFoundError: No module named 'cgi'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'htmlmin' when getting requirements to build wheel